### ISSUE TITLE
Caught an exception data of movie

### ISSUE THREAD

**Issue by internalG** [trakt/api-help#108]
https://trakt.tv/movies/dangerous-odds-2023

It's a maybe release of 2023, but Released field is December 31, 2018. Source data pollution?

**Comment by internalG** [comment]
And can we say the slug is not stable but id of trakt will never change?

**Comment by rectifyer** [comment]
The data has since been updated on TMDB, and refreshed on Trakt. So it's not really data pollution, but rather incomplete/bad data on TMDB that has since been corrected.

https://trakt.tv/movies/dangerous-odds

The Trakt ID is the best thing to use that never changes, yes. The only time it could be an issue is if duplicate movies/shows are added. In that case, the duplicates are removed which would also remove the Trakt ID.
