### ISSUE TITLE
How to get watched and watching tvshows?

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#117]
Is there any way to get `watched` (tvshow which is completely watched) and `watching` (tvshow whose still few episodes are left to watch)
As of now the `getwatched` returns all tvshows with even a single episode watched.
Or do we have to `cache` all the stuff in app?

**Comment by Kashish-Sharma** [comment]
Or can we get `extended-info` for seasons also in `Get Watched`?

**Comment by tysonkerridge** [comment]
What you seem to be asking for is more or less what the "Show Progress" endpoint does. I imagine there's no "watched" or "watching" due to shows having episodes continually airing, and even "ended" shows potentially "coming back"/being renewed and therefore never really ending. What you'd need to do is cache the show episode info, and use the user's watched data to determine if they've completed it or not.
