### ISSUE TITLE
Is there a way to query a single history item?

### ISSUE THREAD

**Issue by lostfocus** [trakt/api-help#121]
Let's say I have the ID from an item of the user history API - is there a way to query the API for that history item?

**Comment by tysonkerridge** [comment]
Do you mean you have just the unique Int64 `id` of the history item and want to get the item it relates to, such as the movie or episode? I don’t think that’s possible. As far as I know all that’s really used for other than a unique identifier is to be able to delete the history item. 

If you retrieved the history item, it would have come with the related item, so perhaps you should keep a reference to what that is alongside the history item `id` so that you can get it using that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lostfocus** [comment]
Actually my use case is the other way around - I do have the history item like in the example from the docs stored:

```
{
    "id": 1982346,
    "watched_at": "2014-03-31T09:28:53.000Z",
    "action": "scrobble",
    "type": "movie",
    "movie": {
      "title": "The Dark Knight",
      "year": 2008,
      "ids": {
        "trakt": 4,
        "slug": "the-dark-knight-2008",
        "imdb": "tt0468569",
        "tmdb": 155
      }
    }
  },
```

and I want to check if that item still exists. My idea was to query the API for that item id and remove it from my data storage when the API returns a 404. Maybe there is a better way?

**Comment by tysonkerridge** [comment]
Ahh. In that case, I guess what I said still applies, in that I don’t think the API currently supports anything like that. Feel free to wait for an offical response though.

The only accurate way I know would be to check the history endpoint again and diff the results (perhaps filtering by the history item, Eg. `/sync/history/movie/4`, depending on your use case). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
@lostfocus Yes, you can do what @tysonkerridge suggests to check the history endpoint. Alternatively, you can cache all watched items using https://trakt.docs.apiary.io/#reference/sync/get-watched/get-watched and do local comparisons. We recommend polling the `/sync/last_activities` endpoint to know if you need to pull down new info. This is how the website works actually, once it detects a newer timestamp, it re-syncs that specific info.

**Comment by lostfocus** [comment]
Okay, thanks. I'll try it that way then. :)
