### ISSUE TITLE
Needed some help regarding app's behavior

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#122]
When a `season` or an `episode` of a particular `show` is watched, `trakt` marks the whole show as watched ( not the whole show, but returns the show in watched endpoint ).

So, if there's such a case, should we allow the user to add the `show` to the watchlist?
If so, then next time when we sync the local DB with `trakt`, `show` will again be returned by `watched` endpoint because few episodes or a season is still `watched`.

As of now in my app:
If `show` is in `watchlist` you can:
* Add to watched.
* Remove from watchlist.

If in watched:
* Rewatched
* Not watched

If none, then:
* Add to watchlist
* Mark as watched

What's the right behavior?
Thanks

**Comment by tysonkerridge** [comment]
You can verify using the website but what you have is correct except if something is watched you can still add it to your watch list. It’s just that if at the time you Mark as watched the item was on the watch list, it’s automatically removed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
The watchlist shouldn't be used to continually re-add shows to it. We already know what the user is watching with the `/sync/watched/shows` endpoint. Any show in there doesn't mean it is 100% watched, but rather they've watched at least 1 episode of the show.

I recommend caching that watched data locally, then do local comparisons to your show level data. You can then figure out if they have any unwatched episodes. This is much cleaner and faster since you're doing local comparisons.

**Comment by Kashish-Sharma** [comment]
@rectifyer It'd be really convenient while returning show progress, `aired_episodes` could also be returned, then the comparison will be really easy. As of now I fetch `show summary` separately to get `aired_episodes` and then compare.

**Comment by rectifyer** [comment]
We don’t return that since your watched data might be cached for a while, and that number would get inaccurate.
