### ISSUE TITLE
Scrobble with absolute episode number

### ISSUE THREAD

**Issue by sttz** [trakt/api-help#15]
Doing scrobbling on Crunchyroll, all I have is the absolute episode number. It would be great if `/scrobble/start` would accept `number_abs` in the episode object.

The only workaround I've found right now is to load `/shows/{id}/seasons/{season}?extended=full`, which does return `number_abs` but is very wasteful.

On a related note, it would also be good to have a generic way to look up an episode by its absolute number, e.g. by having an episode endpoint in the form of `/shows/{id}/episodes/{number_abs}`.

**Comment by rectifyer** [comment]
`/scrobble` and `/checkin` methods now accept `number_abs` for episodes.

https://trakt.docs.apiary.io/#reference/scrobble/start
https://trakt.docs.apiary.io/#reference/checkin/checkin

For the other request, please open a separate issue for that. It's actually quite a bit more involved to support absolute numbering to get episode data since all the associated endpoints (translations, etc) would also need to support it.

**Comment by sttz** [comment]
Works great, thanks for the quick response!

I don't have a use case right now for the endpoint, since I'm always going through `/scrobble` first and can then use the returned id. I'll open an issue when a case comes up where I need it.
