### ISSUE TITLE
Support sorting for the /ratings endpoint

### ISSUE THREAD

**Issue by milokmet** [trakt/api-help#185]
It would be great if the /users/id/ratings endpoing will support sorting. I would like to sort the result by rating too. Now it seems that the results are sorted by rated_at.

I would like to implement pagination sorted by rank, and now it is possible only with large limit set, sorted the list by rank and display the result for selected page. It would be easier and more resources saving, if the /results endpoint will return only the slice of resultset sorted for the selected page.

**Comment by rectifyer** [comment]
I'd recommend a few ways to approach this.

1) Get all ratings for the user, then sort locally in you app. This is also useful to keep this info locally so you can quickly grab the user's rating for an item.

2) Send a rating in the API method. For example, in your app you could have 10 "pages" that correspond to ratings 1-10 and when a user loads that, you get all rated items for that specific rating number.

Option 1 is the intended approach and having the app handle any sorting. We don't implement a lot of sorting in the API so that apps can all pull from the same cached data.
