### ISSUE TITLE
Episode air-time Time Zone adjustments for the US

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#21]
It's come to my attention that I may be converting some episode air-times "incorrectly" when it comes to broadcasting times in the US. I say incorrectly in quotes because to me it's actually correct, but when I compare to the Trakt website it's wrong. I'm from Australia, so I think it's because there might be some extra logic I'm missing and not understanding when it comes to air-times in the US.

As an example on the Trakt website,

If I have my Trakt Time Zone set to `(GMT +10:00) Brisbane` (my local time zone) in the [Trakt settings](https://trakt.tv/settings) and I open an episode such as [Game of Thrones S01E01](https://trakt.tv/shows/game-of-thrones/seasons/1/episodes/1) the date it airs is set to `11:00 AM`.

If I then change my Time Zone to `(GMT -5:00) Eastern Time (US & Canada)` and reload the page, it adjusts to display `9:00 PM` as expected. 

Now, here's the bit I don't get, if I change my Time Zone to `(GMT -8:00) Pacific Time (US & Canada)` and reload the page, it _also_ displays `9:00 PM`. With my logic, it displays as `6:00 PM` due to the 3 hours difference in the Time Zone. 

I tried a few of the other Time Zones around the US offsets, and they have similar behaviour. 

My question then is, whats the best way to handle this logic? Is there some standard that I need to conform to when it comes to US air-times, or any others I should know about? Because for any other dates such as the dates for comments, they're adjusting as expected (and on the website, are using my system time zone, rather than the Time Zone set to the Trakt settings which seems odd). 

Perhaps this information, if any, could be included in the [**Dates** section of the API Documentation](https://trakt.docs.apiary.io/#introduction/dates)?

Any help would be appreciated!

**Comment by Daeymien** [comment]
Using GoT as the example, HBO air the show at 9PM on their East feed and then 9PM on their West feed. (East feed actually usually re-airs the episode again 3 hours later when it's first airing on the West feed).

So, 9PM is actually correct for both GMT-5 and GMT-8 in this scenario.

Depending on the show they can be aired simultaneously on the west coast (I believe Saturday Night Live does this still), or tape-delayed to air in the same time-slot locally.

**Comment by tysonkerridge** [comment]
Cool, thanks for the info, and yeah that makes sense why they only list the first airing etc. I suppose my goal is to match as closely as I can to what Trakt has, because that's what Trakt users expect, especially when trying to send notifications about the episode airing. There just happens to be a bit of inconsistency so I can't really pin down what that logic is. 

Trying to work it out myself isn't going very well, as I tried setting my time zone to GMT-5 and GMT-8 and checking some random episodes in the calendar. It appears that shows that aren't in the US are adjusted directly based on the time zone set. For example, [Ambulance Australia S02E01](https://trakt.tv/shows/ambulance-australia/seasons/2/episodes/1) shows up as 12:30am for GMT-8 and as 3:30am for GMT-5 probably because its an Australian network, however as in the [original Game of Thrones example](https://trakt.tv/shows/game-of-thrones/seasons/1/episodes/1) with HBO being a US network, its displaying GMT-5 time (9:00pm) for both. 

Continuing with the GoT episode, trying say GMT-10 (Hawaii) still shows 9:00pm, and then GMT-11 (Midway island) jumps to 2:00pm. GMT-3 (Greenland) also shows 9:00pm, and GMT-2 (Mid-Atlantic) shows 11:00pm. So its as if time zones between -3 and -10 all use -5 time zone offsets, except as you mentioned, -6 (Central) and -7 (Mountain) have that slightly "wonky" adjustment. All time zones outside that use the offsets directly etc.

So I guess I can make it so that for shows who's airing information or country of origin is from the US/Canada and related time zones, I do something special like the above, but I just wanted to get confirmation that that's how it works and some details of which time zones have special rules, rather than implement something and then have users come back and say its not working as they expect (which is the reason I was investigating to begin with haha).

**Comment by Daeymien** [comment]
> with HBO being a US network, its displaying GMT-5 time (9:00pm) for both.

Technically HBO isn't a network in the traditional sense. Since it's a cable/premium network, the local providers can pick which feed they want to offer to subscribers from the East or West (or both). Sorta beside the point of the discussion, but I've seen really odd things because of it.

I checked the upcoming listings for a few pre-recorded HBO shows in the different time zones. Seems that Mountain pulls from the West feed so, for example, [Last Week Tonight](https://trakt.tv/shows/last-week-tonight-with-john-oliver) airs at 00:00 Mountain, 23:00 Pacific. Alaskan airs at 22:00, and Hawaii airs at 21:00 which follows that they both use the West feed as well.

That said, switching Trakt to GMT-10 shows that show airs at 22:00 and GMT-9 at 23:00, which is an hour off of the correct airing. So, not quite sure how the offset logic is working on the back-end there.

> some details of which time zones have special rules

You'll have a fun for US with that one, depending on how granular you want to be. Hawaii and Arizona do not observe DST. Last year California and Florida voted to observe DST year-round, pending congressional approval. Then you have states which span two time zones (at least for that and the latter three, you're only worried about the zone and not the specific state). We're a mess. haha Though, at least we haven't gotten into the GMT-X.5 territory yet.

Coming back around, for premium networks, most major US (not sure about CA) providers offer both East and West feeds as part of the package for the channel. So, you could somewhat fudge it and push 2 notifications for both East and West feeds airings, since it _is_ airing if they tuned whichever feed.

From my LWT example, matching what Trakt has for airing (at least in Alaska and Hawaii) would actually generate the "this isn't working right" issue.

**Comment by tysonkerridge** [comment]
Oops wasn’t meant to close... Haha wow, almost tempted to not bother unless I had something concrete to go on. Maybe I’ll leave it as is for now. Thanks for your help so far! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tysonkerridge** [comment]
Hey @rectifyer, would it be possible to get a quick overview of how you guys deal with these offsets on the Trakt website? Thanks in advance!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
The above assumptions are correct. There are special cases for US based shows and US based time zones. As mentioned, if a show airs at 9pm on the east coast US, it also airs at 9pm on the west coast US. Those are obviously different times when looking at a constant time zone such as UTC.

On the Trakt website specifically, we use the user's selected time zone (https://trakt.tv/settings). If that is blank, or the user is not signed in, we use a library called `moment` to get their time zone from their web browser. We then use `moment` (for all users) to adjust and print out the datetime in their time zone and with their selected formatting.

**Comment by tysonkerridge** [comment]
Aright thanks, I’ll see what I can do in regards to the special US cases, doing my best to compare with the website and go from there. Thanks again @Daeymien for your input also! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
