### ISSUE TITLE
Unwatch/Remove stuff from Watched

### ISSUE THREAD

**Issue by tomacotuna** [trakt/api-help#218]
Heyy,

So i am trying to integrate Trakt.tv api within my app for sync capabilities/backup. I was looking at how to sync the data and found the `sync/watched/type` and `sync/watchlist/type` which would allow me to get the Trakt.tv data about the shows and movies a person watch or is planning to watch. But I am a bit unclear how I should deal with the following scenario:

Lets say I sync my data with Trakt.tv at app launch and then a user decided to remove a Movie from its watched lists, how to I signal this to Trakt.tv I can't seem to have the ability to remove watched data, only watchlist. So if I cant remove it and the user resets the app the title will be back there because of the app launch sync with Trakt.tv

What api/method should be used to remove a titlle from watched in this case?

**Comment by tysonkerridge** [comment]
You'll need to look at the History data/endpoints in order to remove history but what you send when removing depends on which data you want to remove. 

https://trakt.docs.apiary.io/#reference/sync/get-history
https://trakt.docs.apiary.io/#reference/sync/add-to-history
https://trakt.docs.apiary.io/#reference/sync/remove-from-history

You can send the items from the [watched endpoint](https://trakt.docs.apiary.io/#reference/sync/get-watched/get-watched) to the [remove endpoint](https://trakt.docs.apiary.io/#reference/sync/remove-from-history) however that will remove _all_ plays (eg. if I've watched a movie twice at different times (two plays), and you send the movie to the remove history, both those plays will be removed.
