### ISSUE TITLE
Getting 429 errors (Too Many Requests)

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#219]
Hi,

I'm getting `429 Too Many Requests` errors back from the API. I'm getting this a lot because of the way the To Watch and sync is implemented in our apps and because we never thought they would be a quota or something like that in place.

Should we update our app to take this into account? Do we have more info on the number of requests we can do in what time? Do we have a `Retry-After` header we can use?

Thanks for the info!

**Comment by linaspurinis** [comment]
Was going to create the same issue. Even after several requests to API, getting errors: 
`429 API rate limit exceeded. Please wait 11 seconds then retry your request.`
Never happened before, is this some temporary or permanent limitations?

**Comment by rectifyer** [comment]
We were testing out API limits last week to gather some stats, but we reverted the change which stopped the 429 errors. We'll be testing out some update rate limiting this week. The goal is to prevent poorly coded apps from spamming the API, but while not affecting correctly coded apps from using the API as normal. 

We recommend handling the 429 errors and the API docs have an example of the info that is sent back. We've had the 429 documented, but need to start enforcing more strict rate limits to deal with the recent performance issues.

https://trakt.docs.apiary.io/#introduction/rate-limiting

**Comment by Prinz23** [comment]
I see in the documentation it says to wait to the time `until` returns in the `X-Ratelimit` header. But this is problematic because of timezones and regular changes of them. For example a change of DST date which happens quite often would then result in the App waiting potentially an extra hour.

The App would have to convert local time to Zulu which can be wrong when the timezone changed (DST changes or others). It would be more useful and less problematic if a field `seconds` or similar would be returned with the value how many seconds to wait. This would be then timezone convert error independent.

**Comment by kevincador** [comment]
@rectifyer will you also support the standard `Retry-After` header (indicating how long to wait before making a new request in seconds)? During my tests last week I was it and have started an implementation based on that header. Would be awesome if you could.

I understand you'll do more tests this week. Does that mean that we should already update our apps for this?

Another question is if this rate limit is linked to our app-id or to the user's ip or to something else?

Thanks for the info!

**Comment by rectifyer** [comment]
@kevincador yes, there will be a `Retry-After` header returned as well, I'll update the API docs. I would recommend updating your apps to handle the header yes, we're still in the testing phase but it's good to handle it. It is linked to the user's IP currently. 

@Prinz23 the `until` is in UTC like all other timestamps we return. That should be fine to use in your app and I don't believe there should be any conversion issues with it.

**Comment by JackDandy** [comment]
Hello @rectifyer

You may be aware that the library called `Requests` is the defacto HTTP library for Python applications cross platform. A dependency of it is urllib3 and only yesterday did they push a commit where the message in the changes.rst file reads... 
```
Fix retry backoff time parsed from ``Retry-After`` header when given
  in the HTTP date format. The HTTP date was parsed as the local timezone
  rather than accounting for the timezone in the HTTP date (typically
  UTC) (Pull #1932, Pull #1935, Pull #1938, Pull #1949)
```
This fix will not propagate to many peoples machine for months at the best case.

As you can see, there are clearly issues converting and using any full date system, locales, bugs in libraries, systems not set correctly, and other issues. 

Can you please make it easier for application developers by simply having some kind of SecondsUntil:`Integer` header, where no conversion is required and where it would not matter if an enduser machine has correct locale, correct date/time, or whatever, because the number of seconds to wait, is simply that.

Please reconsider to make your goal of getting apps to easily adopt and back off from hammering your server easier. It takes near zero developer effort, and is far less issue prone, to simply pop a response number of seconds into a `wait until` next request function, don't you agree ?

Thanks.
Jack

**Comment by JackDandy** [comment]
Hello @rectifyer

You may be aware that the library called `Requests` is the defacto HTTP library for Python applications cross platform. A dependency of it is urllib3 and only yesterday did they push a commit where the message in the changes.rst file reads... 
```
Fix retry backoff time parsed from ``Retry-After`` header when given
  in the HTTP date format. The HTTP date was parsed as the local timezone
  rather than accounting for the timezone in the HTTP date (typically
  UTC) (Pull #1932, Pull #1935, Pull #1938, Pull #1949)
```
This fix will not make it to many peoples machines for months at the best case.

As you can see, there are clearly issues converting and using any full date system, bugs in libraries, systems not set correctly (e.g. locales), and surprisingly many others.

Your response text in messages is like `429 API rate limit exceeded. Please wait 30 seconds then retry your request` - this text may vary or change, so can you place that number into a response header field so that it is always explicit.

Please reconsider to make your goal of getting apps to easily adopt and back off from hammering your server easier. It takes near zero developer effort, and is far less issue prone, to simply pop that response number of seconds into a `wait until` next request function, don't you agree ?

Thanks.
Jack

**Comment by rectifyer** [comment]
The `Retry-After` is the number of seconds, not a timestamp.

**Comment by kevincador** [comment]
@rectifyer I would like to test my implementation regarding this. Would it be possible to enable this on staging or to communicate when you enable it next for your tests on production?

Also, do you have an ETA for when this will be live?

Thanks!

**Comment by rectifyer** [comment]
Closing this topic since I just posted an [official announcement](https://github.com/trakt/api-help/issues/220) which can be a more global place to discuss.

@kevincador this will be live today with the limit mentioned in the API docs. I'm also in the process of rebuilding the staging server since it died recently.
