### ISSUE TITLE
Add items to collection example body needs update

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#226]
It looks like the body example on https://trakt.docs.apiary.io/reference/sync/add-to-collection/add-items-to-collection was copy / pasted from another request. Doesn't show any of the media object post data attached.

**Comment by rectifyer** [comment]
The metadata is optional, which is why it's not included. However, I updated the example at https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection with what it should look like. Basically any level you send (movie, show, season, episode) can optionally accept the metadata.
