### ISSUE TITLE
Missing tmdb id for some shows

### ISSUE THREAD

**Issue by luisrecuenco** [trakt/api-help#24]
Some TV Shows like [Doom Patrol](https://trakt.tv/shows/doom-patrol-2019-138095), or [Our Planet](https://trakt.tv/shows/our-planet-2019) don't have the proper tmdb id.

**Comment by rectifyer** [comment]
Based on the URLs, my guess is there are duplicate shows on Trakt that need to be cleaned up. TMDB would also need its entry updated to use the correct TVDB ID. With new shows, people add them to TVDB multiple times, they remove them since the show hasn't aired yet, and the cycle keeps repeating which creates a bunch of duplicates on Trakt with different (and invalid) TVDB IDs.

It would be best to post at support.trakt.tv and include the correct Trakt link along with any duplicate links that should be removed. Thanks!
