### ISSUE TITLE
Endpoint to get user rating of a movie?

### ISSUE THREAD

**Issue by leepeuker** [trakt/api-help#253]
Hey guys, I am sorry if it is obvious and I'm just blind, but I cannot find a way to get the rating of one user for one movie (e.g. specified by its trakt id). Can anyone help me?

**Comment by tysonkerridge** [comment]
Reminder to use the new [Discussions](https://github.com/trakt/api-help/discussions) tab instead (See https://github.com/trakt/api-help/issues/251)

As for your query, I don't believe it's possible. Unless something has changed, the suggestion is to sync the users ratings. See this comment: https://github.com/trakt/api-help/issues/175#issuecomment-621903258
Otherwise could reduce the info by using the `type` filter, at least, on the ratings endpoint (https://trakt.docs.apiary.io/#reference/users/ratings/get-ratings).

**Comment by rectifyer** [comment]
Yes, you should sync all the ratings then do local comparisons to know what the user has rated.
