### ISSUE TITLE
Reset Watched Progress API

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#3]
I just noticed there is a "Reset Watched Progress" section on the website to re-watch a show. Is this functionality coming to the API soon?

**Comment by rectifyer** [comment]
You can get the reset items from the API currently using https://trakt.docs.apiary.io/#reference/users/hidden-items/get-hidden-items with **section** = `progress_watched_reset`. 

The show progress https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress also contains a `reset_at` value so you can re-calculate the progress in your app.

There isn't currently a way to reset from the API since it is a VIP feature on the website. We don't currently have any VIP only features ported to the API.

**Comment by MaxHasADHD** [comment]
Do you have plans to bring VIP features to the API in the future right now or unsure?

**Comment by limbero** [comment]
I asked a question about this [in the support forums](https://support.trakt.tv/forums/188762-general/suggestions/3684269-restart-tv-show-progress-while-keeping-episode-wat) and thought I would elaborate a little after being referred here.

First, I think the information doesn't really make sense to get from the _Get hidden items_ call, simply because reset shows aren't something I think of as hidden, but that may be just me. 

Second, I think the way it's displayed in hidden items is confusing. The only timestamp displayed is `hidden_at`, which is the moment I clicked the button to reset the show, but not the actual date I marked for the start of the reset, that information can only be retrieved from the _Get show watched progress_ call (there called `reset_at`).

My suggestion would be to

 1. Add a `reset_at` (or maybe more clearly? `reset_from`) field to the _Get hidden items_ call
 2. Add the `reset_at` field as a sibling to `last_watched_at` and `last_updated_at` in the _User > Get watched_ call. That's where I intuitively expected to find it, especially when the other place to get it is in the _Get show watched progress_ call .

**Comment by rectifyer** [comment]
1. That is actually a bug _(now fixed)_ so the correct date is now used for `hidden_at`. I can't add another field since that API call is shared across all the different types. I agree its a little confusing, but the data is correct now.

2. I am looking into this one still.

**Comment by rectifyer** [comment]
in regards to item 2, this will be available later this week in the API. It will return a `reset_at` date in the `/sync/watched/shows` `/users/:id/watched/shows` methods.

The progress still needs to be reset using the website, this update is just to read the reset date if the VIP user has set it.
