### ISSUE TITLE
Get if review liked by user

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#31]
How to check if the user liked a review?
For eg., user likes a review for a movie and after a few days opens review for the same movie, how to check whether the reviews are already liked by the user or not.

**Comment by tysonkerridge** [comment]
I’m pretty sure you would need to sync the users likes using the `/users/likes/comments` endpoint https://trakt.docs.apiary.io/#reference/users/likes/get-likes. 

You can find out if they’ve liked something since last syncing with the `/sync/last_activities` endpoint and checking for `comments.liked_at` https://trakt.docs.apiary.io/#reference/sync/last-activities/get-last-activity

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
Thanks a lot.
I can maintain a local cache and sync it from time to time.
