### ISSUE TITLE
Popular endpoint filtering by multiple years.

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#44]
Hello,

Would it be possible to filter the popular endpoint by multiple years separated by commas instead of having to do one request by year ?

Thanks

**Comment by rectifyer** [comment]
You can send a range such as `2015-2018`.

**Comment by jonathanantoine** [comment]
Thank you ! I noticed that if I start by the "most recent year" (2018-2015) the API returns nothing by the way.

**Comment by rectifyer** [comment]
Yes, it needs to be a range starting with the earliest year.

On March 15, 2019 at 8:58:39 AM, jonathanantoine (notifications@github.com)
wrote:

Thank you ! I noticed that if I start by the "most recent year" (2018-2015)
the API returns nothing by the way.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/trakt/api-help/issues/44#issuecomment-473342507>, or mute
the thread
