### ISSUE TITLE
Comment--spoiler detection 

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#62]
Hello,

Would it be possible that the API automatically detect [spoiler] tags in comments and set the "spoiler" property to true ? Or maybe a new one "contains Spoiler"? 

Right now, I have to look for this particular string in every comments and it's not really nice for my CPU 😁

Thank you!

**Comment by rectifyer** [comment]
Hmm, is it that intensive to do a string search? It seems like you'd only need to do this when rendering the comment and converting the markdown syntax which you are presumably also doing.

**Comment by jonathanantoine** [comment]
I think that it would be better to do it once for all a comment is posted (or edited) than to let every device doing it (for every displayed comment) each time no? 

I do not (yet) convert markdown to "native rich text" as I didn't find an elegant and performant solution.

**Comment by rectifyer** [comment]
I think this should still be up to the app to render the inline spoilers since you'll need to do some sort of logic to blur it out, even if we sent an additional field. On the Trakt website for example, we have a function that we use wherever comment text is displayed. That function does things like check for inline spoilers, render emjois, and render markdown.

**Comment by jonathanantoine** [comment]
OK, let's go for this then 😊

(this could have been a first step implementation help for app)

((thanks a lot for this API and the time you spend answering us 😊))

**Comment by tysonkerridge** [comment]
I think maybe @jonathanantoine was meaning for the API to set the `spoiler` flag to true if a `[spoiler]` tag is contained in the `comment` parameter, perhaps separate to the client sending the `spoiler` flag as it already can when [posting a comment](https://trakt.docs.apiary.io/#reference/comments/comments/post-a-comment).

But yeah, in terms of how its necessary to doing some processing of the string in order to adjust for displaying emoji/markdown etc, you can do this check at that point and store that flag separately if you're not assuming the `spoiler` flag sent with the Comment object is accurate enough. The server can't do anything more to help with rendering, as thats per client to set up the UI.
