### ISSUE TITLE
Hoping for some quick help?

### ISSUE THREAD

**Issue by dxfan227** [trakt/api-help#65]
I am trying to pull the trakt information for upcoming schedule ( Tonights episodes that are airing) to my app ( a magic mirror). There is a module, https://github.com/Kiina/MMM-trakt, which allows this. I set it up and its working from what I can tell. The only problem is that it's pulling in shows 1 day late....ie I see yesterdays shows/date . 

So far to trouble shoot I have
1. Posting in that git for help
2. Tested a test.js file with node the includes some calls to moment.js, my date is correct ( system wide I assume)

I am very green at all coding etc....would anyone be willing to take a look at that code and see if there is something I may have messed up?

**Comment by tysonkerridge** [comment]
Chances are it’s a time zone issue. The API works on UTC time for all dates. I could be slightly wrong here, but as far as I understand, when you say you want the calendar items for `2019-04–24`, that’s going to return items from 2019-04-24 00:00 GMT+0 to 23:39, if that makes sense. So if you’re wanting all of the items for the user’s time zone, you may need to ask for the day before/after on top (using the `days` parameter), and then filter out returned results which aren’t within your expected dates. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dxfan227** [comment]
Its very strange because when I ask it to show today and tomorrows shows….tomorrows shows are correct…..so it knows the right date.

**Comment by tysonkerridge** [comment]
So I spent a little while/a few iterations working this out, but my previous comment covers the general solution. As a broken down example to explain, check out the `/calendars/all/shows` endpoint. 

The first result will generally have a `first_aired` timestamp of something like `2019-04-26T00:00:00.000Z`, where the `00:00:00.000Z` is 00:00 UTC because the date used for the results is in UTC (as with like 99% of the dates you send/receive using the API).

So if your local Timezone is something other than UTC (GMT+0), you need to account for that offset when converting your expected start date to UTC and using that as your `start_date`, and using the `days` parameter to make up the difference of the offset in order to pick up anything outside the offsets.

Using 26 April 2019 as an example day:
If your Timezone is GMT+10, you’ll want to use pretty much the day before, as **2019-04-26 00:00 GMT+10** is **2019-04-25 14:00 GMT+0**. So the `start_date` parameter you want is `2019-04-25`. However because that will return results from **2019-04-25 00:00 to 23:59 GMT+0**, you also need to add one day in total in order to receive up to **2019-04-26 14:00 GMT+0**, so the `days` parameter you want is `2`. Meaning your endpoint is `/calendars/all/shows/2019-04-25/2`.

Now, you’ll receive items from **2019-04-25 00:00 GMT+0** to **2019-04-26 23:59 GMT+0**. This means in order to get only the items from those results that fall within your original start/end date (**2019-04-26 00:00 to 23:59 GMT+10**), you need to filter out all the items outside those times.

For a negative GMT (eg. GMT-8), you do the same, pretty much (logic is exactly the same), but for the sake of the example, you’re going the other way (basically, `start_date` is `2019-04-26` and still using `days` parameter of `2` to make up the difference, seeing as **2019-04-26 00:00 GMT-8** is **2019-04-26 08:00 GMT+0** meaning you need to get up to **2019-04-27 08:00 GMT+0**. You should end up with items between **2019-04-26 00:00 GMT+0** and **2019-04-27 23:59 GMT+0**. Once again you’re going to need to filter out anything outside **2019-04-26 00:00 to 23:59 GMT-8**.

I’m unsure if I can explain it any better than that heh. The important thing is that the dates you use for the endpoint are in UTC, hence why for GMT+10 you’re technically using the day before through to the day you’re in, and for GMT-8 you’re using the day you’re in through to the next day. This would be why you’re seeing somewhat “correct” results when using tomorrow’s date and seeing some of tomorrow’s results, but you’ll find it’s also including some of the day before/after as well due to the UTC logic. Using the `all` endpoint is likely the best way to test as it should have items ranging from 00:00 to 23:59 in any time zone (although also has a lot of items for each request lol). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dxfan227** [comment]
Thank you for the info. I have forwarded it to the modules developer 

https://github.com/Kiina/MMM-trakt

I am hoping it will be useful information for them to implement a fix if indeed this is the issue.

**Comment by rectifyer** [comment]
Thanks to the other devs for chiming in with some very detailed info! You guys are correct that since the calendar methods use UTC you'll need to account for that and do some additional logic in the app based on the user's selected time zone.

**Comment by dxfan227** [comment]
Thank you, the comments here were forwarded to the dev of the module and he was able to implement the fix! Amazing wish I could learn how to do it on my own
