### ISSUE TITLE
403 Errors on Chinese Internet

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#92]
So I’ve got a user who seems to not be able to use the app due to receiving errors for, I’m assuming, all API endpoints. What’s most interesting is the endpoints are returning 403s, with the one I got screenshots/videos of being the Trending Movies endpoint. They also attempted to sign in but end up getting errors once signing in, which I’m assuming is the Get Token endpoint.

They’re apparently seeing these issues when connected to their internet in China, which I assume could be part of the issue, but they seem to be able to log in successfully to the Trakt website, and also they seem to be able to use a VPN to connect outside of China and the app works when connected to that.

From my own debugging, I don’t see these issues else I’d have looked into it further myself, but also don’t have a way to test on a Chinese connection either.

Any ideas on what additional information I’d need to get from the user in order to work out what could be the issue in order to find a solution? I’d most likely have to make some changes to provide them some way to send me some logs, but I’m not sure what to include in the logs. 

Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
My guess is Cloudflare is detecting a threat and preventing it from loading. On the website, they would put up a captcha for the user to complete, but I'm not sure what they do on an API call like this. There might be additional headers send in the API response, but I'm not sure what we can do since we need to keep threat protection in place.

**Comment by tysonkerridge** [comment]
Ahh yes, the user sent me a screen recording in which they  were directed to a captcha entry, but then nothing seemed to ask them for Trakt username or password. Perhaps they did that in a previous session before recording so it kept them logged in or something when they tried to access the authentication sign in link again.

Thanks, I’ll let them know and see if I can get some more details.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShaneQi** [comment]
|Original|Translated|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/7324708/61679256-4192f780-accb-11e9-90cb-b6cd1ec50c81.png)|![download](https://user-images.githubusercontent.com/7324708/61679643-76ec1500-accc-11e9-8296-301fba8ffe16.png)|

My app's Chinese users complaint that the API stopped working recently and one of them found out that requests that are sent to both trakt.tv and api.trakt.tv are asked to enter a verification code.

I was hoping you could contact CloudFlare and find a solution. They might be able to provide help with a secure config for the API that can prevent the CAPTCHA.

**Comment by tysonkerridge** [comment]
That captcha screen in the screenshot is the same as the one in the screen recording I was talking about.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShaneQi** [comment]
More info:

```
curl --include \
     --header "Content-Type: application/json" \
     --header "trakt-api-version: 2" \
     --header "trakt-api-key:<REDACTED>" \
  'https://api.trakt.tv/shows/trending'
```

I sent a cURL command to once of my users in China.

And the response he got back is (I'm trying to get a text version of the response from him):

![image](https://user-images.githubusercontent.com/7324708/61680055-e3b3df00-accd-11e9-921d-5b19d5c7c666.png)

**Comment by rectifyer** [comment]
Ok, so yeah for a captcha challenge is being presented from Cloudflare due to a potential threat. I'll have to research if its possible for Cloudflare to handle it differently if the request is `application/json`.

**Comment by rectifyer** [comment]
Following up on this, there doesn't seem to be a way to separate the challenge captcha and do something differently for the API. This seems like a feature request for Cloudflare, but I'm not really sure what can be done differently. There isn't a way for us to ask the user for additional info via the API.

**Comment by ShaneQi** [comment]
@rectifyer Thanks for the update.

IMO, this is a flaw on the Cloudflare/Baidu side that __API__ requests are challenged with captcha but there isn't an __API__ to get the captcha for users and send users' captcha input back. I agree that nothing can be done by us differently. 

Did you explained the exact situation, in which our affected users are, to Cloudflare to explicitly request a feature/fix? I'm asking because:

1. Our affected users are in a special situation (challenges requests are API requests and (this only happens for users in areas that Cloudflare partners with Baidu), it's easy for them to get our problem wrong.
2. I searched this problem a little bit and many questioners asked the same question but walked away by changing firewall settings (we don't want to do that to compromise our protection). We need to tell Cloudflare that it's their system flaw, not our configuration problem.
3. You are at a better place to request Cloudflare for a feature/fix because you are the direct customer of Cloudflare (correct me if I'm wrong).
4. If we could have a Cloudflare issue/ticket, it's better to track the progress.

**Comment by ShaneQi** [comment]
@rectifyer 

Recently I got multiple negative feedbacks on my TV show tracker app from Chinese users because of the captcha issue. They don't understand the issue under the hood, they only know my app isn't usable anymore. I feel sorry for them. 

I'm considering building a server (located in US) to setup a reserve proxy for Chinese users. My server will call Trakt api in the behave of my users to retrieve the resources they need.

I wanted to have your input on this before starting doing it: is there any reason that you do not recommend me to use a reserve proxy server to solve the particular issue our Chinese users are experiencing?

**Comment by rectifyer** [comment]
That is actually a pretty cool idea and way to handle it. Are you just planning to spin up a cloud server (AWS, Google, etc) and run API calls through there if you detect the person is located in China? I guess the only question would be with authenticated API methods, but I don't see any issues with doing this.

**Comment by ShaneQi** [comment]
@rectifyer 

Yes what you said is exactly what I've been thinking.

There might be issues like you mentioned authenticated endpoints, but since it's just a simple proxy, shouldn't take much time, I'll just go ahead and try it.

Thanks for you opinion, I'll give updates here.

**Comment by Tback1** [comment]
The question is when Cloudflare&Baidu cooperate the api was block by it and the user mostly didn't understand why Trakt will use the baidu , further they worried about it on the private and morality, the Baidu is notoriously on both things.

**Comment by rectifyer** [comment]
I was able to make some adjustments that should help with accessing the API in China, hopefully that helps this issue. Closing for now since I believe this will solve it.
